#ifndef TRAIN_ERRORS_H
#define TRAIN_ERRORS_H

using namespace std;

enum Code
{
  ERR_REGRESS = 0,
  ERR_SURVIVORS = 1,
  ERR_SHORT_ACCEL_TRACE = 2,
  ERR_NO_PEAKS = 3,
  ERR_ALGO_PEAK_COLLAPSE = 4,
  ERR_ALGO_PEAKSTATS = 5,
  ERR_ALGO_MANY_FRONT_PEAKS = 6,
  ERR_ALGO_MEASURE = 7,
  ERR_SENSOR_NOT_LOGGED = 8,
  ERR_ALGO_PEAK_INTERVALS = 9,
  ERR_CAR_SIDE_GAP_RESET = 10,
  ERR_MODELS_EMPTY = 11,
  ERR_ALGO_PEAK_MATCH = 12,
  ERR_ALGO_PEAK_CONSISTENCY = 13,
  ERR_ALGO_PEAK_PARAMETER = 14,
  ERR_ALGO_PEAK_STRUCTURE = 15,
  ERR_ALGO_CAR_STRUCTURE = 16,
  ERR_ALGO_NO_WHEEL_GAP = 17,
  ERR_ALGO_PEAKPOOL_EMPTY = 18,

  // From here on they are vetted
  ERR_UNKNOWN_SAMPLE_RATE = 19,
  ERR_NO_TRACE_FILE = 20,
  ERR_TRUE_TRAIN_UNKNOWN = 21,
  ERR_NO_ALIGN_MATCHES = 22,
  ERR_NO_PEAKS_IN_STRUCTURE = 23,
  ERR_NO_NESTED_INTERVALS = 24,
  ERR_NO_LABEL_SCALE = 25,


  ERR_PATTERN_BAD_FIX = 26
};


#endif

